# ==============================================================================
# Go (Golang) Pipeline Template - Complete Reusable Pipeline
# ==============================================================================
# This template can be used by any Go project by copying it or referencing
# it from nayaksuraj/test-repo
#
# Usage: Copy this file to your repo as bitbucket-pipelines.yml and configure
# the required Bitbucket variables (see bottom of file)
# ==============================================================================

image: golang:1.21

clone:
  depth: 50
  lfs: false

definitions:
  caches:
    go-mod: /go/pkg/mod

pipelines:
  # ==============================================================================
  # Pull Requests - Fast Feedback
  # ==============================================================================
  pull-requests:
    '**':
      - pipe: docker://nayaksuraj/lint-pipe:1.0.0
        variables:
          PRE_COMMIT_ENABLED: "true"
          LOCKFILE_CHECK: "true"
          LINT_ENABLED: "true"
          TYPE_CHECK_ENABLED: "true"

      - pipe: docker://nayaksuraj/test-pipe:1.0.0
        variables:
          COVERAGE_ENABLED: "true"

      - parallel:
          - pipe: docker://nayaksuraj/quality-pipe:1.0.0
            variables:
              SONAR_ENABLED: "${SONAR_ENABLED:-false}"
              SONAR_TOKEN: $SONAR_TOKEN

          - pipe: docker://nayaksuraj/security-pipe:1.0.0
            variables:
              SECRETS_SCAN: "true"
              SCA_SCAN: "true"
              FAIL_ON_HIGH: "false"

  # ==============================================================================
  # Develop Branch - Auto-Deploy to Dev
  # ==============================================================================
  branches:
    develop:
      - pipe: docker://nayaksuraj/lint-pipe:1.0.0

      - pipe: docker://nayaksuraj/test-pipe:1.0.0
        variables:
          COVERAGE_ENABLED: "true"

      - parallel:
          - pipe: docker://nayaksuraj/quality-pipe:1.0.0
            variables:
              SONAR_ENABLED: "true"
              SONAR_TOKEN: $SONAR_TOKEN

          - pipe: docker://nayaksuraj/security-pipe:1.0.0
            variables:
              SBOM_GENERATE: "true"
              SAST_SCAN: "true"

      - pipe: docker://nayaksuraj/docker-pipe:1.0.0
        variables:
          DOCKER_REGISTRY: $DOCKER_REGISTRY
          DOCKER_REPOSITORY: $DOCKER_REPOSITORY
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
          SCAN_IMAGE: "true"

      - pipe: docker://nayaksuraj/deploy-pipe:1.0.0
        variables:
          ENVIRONMENT: "dev"
          DEPLOY_NAMESPACE: "development"
          KUBECONFIG: $KUBECONFIG_DEV

      - pipe: docker://nayaksuraj/notify-pipe:1.0.0
        variables:
          CHANNELS: "slack"
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
          MESSAGE: "✅ Deployed to DEV"
          ENVIRONMENT: "dev"
          STATUS: "success"

  # ==============================================================================
  # Main Branch - Deploy to Staging
  # ==============================================================================
    main:
      - pipe: docker://nayaksuraj/lint-pipe:1.0.0
        variables:
          TYPE_CHECK_COMMAND: "go vet ./..."

      - pipe: docker://nayaksuraj/test-pipe:1.0.0
        variables:
          COVERAGE_ENABLED: "true"

      - parallel:
          - pipe: docker://nayaksuraj/quality-pipe:1.0.0
            variables:
              SONAR_ENABLED: "true"
              SONAR_TOKEN: $SONAR_TOKEN
              QUALITY_GATE_ENABLED: "true"

          - pipe: docker://nayaksuraj/security-pipe:1.0.0
            variables:
              FAIL_ON_HIGH: "true"
              SAST_SCAN: "true"
              IAC_SCAN: "true"

      - pipe: docker://nayaksuraj/docker-pipe:1.0.0
        variables:
          DOCKER_REGISTRY: $DOCKER_REGISTRY
          DOCKER_REPOSITORY: $DOCKER_REPOSITORY
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
          SCAN_IMAGE: "true"
          TRIVY_EXIT_CODE: "1"

      - pipe: docker://nayaksuraj/helm-pipe:1.0.0
        variables:
          LINT_CHART: "true"
          PACKAGE_CHART: "true"

      - step:
          name: 🚀 Deploy to Staging
          deployment: staging
          trigger: manual
          script:
            - pipe: docker://nayaksuraj/deploy-pipe:1.0.0
              variables:
                ENVIRONMENT: "staging"
                DEPLOY_NAMESPACE: "staging"
                KUBECONFIG: $KUBECONFIG_STAGING

      - pipe: docker://nayaksuraj/notify-pipe:1.0.0
        variables:
          CHANNELS: "slack"
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
          MESSAGE: "✅ Deployed to STAGING"
          ENVIRONMENT: "staging"
          STATUS: "success"
          TITLE: "Staging Deployment"

  # ==============================================================================
  # Tagged Releases - Production Deployment
  # ==============================================================================
  tags:
    'v*':
      - pipe: docker://nayaksuraj/lint-pipe:1.0.0
        variables:
          TYPE_CHECK_COMMAND: "go vet ./... && staticcheck ./..."

      - pipe: docker://nayaksuraj/test-pipe:1.0.0
        variables:
          COVERAGE_ENABLED: "true"

      - pipe: docker://nayaksuraj/security-pipe:1.0.0
        variables:
          FAIL_ON_HIGH: "true"
          SAST_SCAN: "true"

      - pipe: docker://nayaksuraj/docker-pipe:1.0.0
        variables:
          DOCKER_REGISTRY: $DOCKER_REGISTRY
          DOCKER_REPOSITORY: $DOCKER_REPOSITORY
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
          IMAGE_TAG: "${BITBUCKET_TAG#v}"
          SCAN_IMAGE: "true"
          TRIVY_EXIT_CODE: "1"

      - pipe: docker://nayaksuraj/helm-pipe:1.0.0
        variables:
          CHART_VERSION: "${BITBUCKET_TAG#v}"
          HELM_REGISTRY: $HELM_REGISTRY
          HELM_REGISTRY_USERNAME: $HELM_REGISTRY_USERNAME
          HELM_REGISTRY_PASSWORD: $HELM_REGISTRY_PASSWORD
          LINT_CHART: "true"
          PACKAGE_CHART: "true"
          PUSH_CHART: "true"

      - step:
          name: 🚀 Deploy to Production
          deployment: production
          trigger: manual
          script:
            - pipe: docker://nayaksuraj/deploy-pipe:1.0.0
              variables:
                ENVIRONMENT: "production"
                DEPLOY_NAMESPACE: "production"
                KUBECONFIG: $KUBECONFIG_PRODUCTION
                DEPLOYMENT_STRATEGY: "canary"

      - pipe: docker://nayaksuraj/notify-pipe:1.0.0
        variables:
          CHANNELS: "slack"
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
          MESSAGE: "🎉 v${BITBUCKET_TAG#v} deployed to PRODUCTION"
          ENVIRONMENT: "production"
          STATUS: "success"
          TITLE: "Production Release"
          MENTION_CHANNEL: "channel"
          CUSTOM_FIELDS: '{"Version":"${BITBUCKET_TAG#v}","Deployment":"Canary → Full Rollout"}'

# ==============================================================================
# Required Bitbucket Variables (mark as secured where indicated)
# ==============================================================================
# DOCKER_REGISTRY           - Docker registry URL (e.g., ghcr.io)
# DOCKER_REPOSITORY         - Docker repository name
# DOCKER_USERNAME           - Docker registry username (secured)
# DOCKER_PASSWORD           - Docker registry password/token (secured)
# KUBECONFIG_DEV            - Kubernetes config for dev environment (secured)
# KUBECONFIG_STAGING        - Kubernetes config for staging environment (secured)
# KUBECONFIG_PRODUCTION     - Kubernetes config for production environment (secured)
# SLACK_WEBHOOK_URL         - Slack webhook URL (secured)
# SONAR_TOKEN               - SonarQube/SonarCloud token (secured) (optional)
# HELM_REGISTRY             - Helm chart registry URL (optional)
# HELM_REGISTRY_USERNAME    - Helm registry username (secured) (optional)
# HELM_REGISTRY_PASSWORD    - Helm registry password (secured) (optional)
