# ==============================================================================
# Reusable Python Pipeline Template
# ==============================================================================
# This template can be included in any Python project with minimal configuration
#
# USAGE:
# 1. Copy this file to your repo as .bitbucket/pipelines/python-template.yml
# 2. Reference it from your bitbucket-pipelines.yml
# 3. Override variables as needed
#
# OR use it directly by copying to bitbucket-pipelines.yml and setting variables
# ==============================================================================

# ==============================================================================
# CONFIGURATION VARIABLES (Override these in your project)
# ==============================================================================
# Required Variables:
#   DOCKER_REGISTRY, DOCKER_REPOSITORY, DOCKER_USERNAME, DOCKER_PASSWORD
#   HELM_REGISTRY, HELM_REGISTRY_USERNAME, HELM_REGISTRY_PASSWORD
#   KUBECONFIG_DEV, KUBECONFIG_STAGING, KUBECONFIG_PRODUCTION
#
# Optional Variables:
#   SONAR_TOKEN, SLACK_WEBHOOK_URL
#   PYTHON_VERSIONS (default: "3.9 3.10 3.11 3.12")
#   COVERAGE_THRESHOLD (default: "85")
#   HELM_CHART_PATH (default: "../../helm-chart")
# ==============================================================================

image: python:3.12-slim

options:
  max-time: 60

definitions:
  caches:
    poetry: ~/.cache/pypoetry
    pip: ~/.cache/pip
    pre-commit: ~/.cache/pre-commit

  services:
    docker:
      memory: 3072

  # ==============================================================================
  # Reusable Step Templates
  # ==============================================================================
  steps:
    pre-checks: &pre-checks
      step:
        name: 🔍 Pre-checks
        caches: [poetry, pip, pre-commit]
        script:
          - pip install --upgrade pip poetry pre-commit
          - poetry check && poetry lock --check
          - pre-commit run --all-files || (echo "❌ Pre-commit failed" && exit 1)
          - poetry install --no-interaction
          - poetry run ruff check . --select=F,E --exit-non-zero-on-fix

    unit-test: &unit-test
      step:
        name: 🧪 Tests (Python $PYTHON_VERSION)
        image: python:${PYTHON_VERSION}-slim
        caches: [poetry, pip]
        script:
          - pip install --upgrade pip poetry
          - poetry config virtualenvs.in-project true
          - poetry install --no-interaction
          - poetry run pytest
              --cov=src
              --cov-report=xml:coverage-${PYTHON_VERSION}.xml
              --cov-report=html:coverage-html-${PYTHON_VERSION}
              --cov-report=term
              --junitxml=test-results-${PYTHON_VERSION}.xml
              --maxfail=5
              -n auto
              -v
          - poetry run coverage report --fail-under=${COVERAGE_THRESHOLD:-85}
        artifacts:
          - coverage-${PYTHON_VERSION}.xml
          - coverage-html-${PYTHON_VERSION}/**
          - test-results-${PYTHON_VERSION}.xml

    type-check: &type-check
      step:
        name: 🔍 Type Checking
        caches: [poetry]
        script:
          - pip install --upgrade pip poetry
          - poetry install --no-interaction
          - poetry run mypy src ${MYPY_FLAGS:---strict}

    quality-scan: &quality-scan
      pipe: docker://nayaksuraj/quality-pipe:1.0.0
      variables:
        SONAR_ENABLED: "${SONAR_ENABLED:-true}"
        SONAR_TOKEN: $SONAR_TOKEN
        COVERAGE_REPORT: "coverage-3.12.xml"

    security-scan: &security-scan
      pipe: docker://nayaksuraj/security-pipe:1.0.0
      variables:
        SECRETS_SCAN: "true"
        SCA_SCAN: "true"
        SAST_SCAN: "${SAST_SCAN:-true}"
        SBOM_GENERATE: "true"
        SBOM_FORMAT: "cyclonedx-json"
        FAIL_ON_HIGH: "${SECURITY_FAIL_ON_HIGH:-false}"

    # ==========================================================================
    # Docker Build, Scan & Push (Uses docker-pipe - eliminates duplicate tool installation)
    # ==========================================================================
    docker-build: &docker-build
      pipe: docker://nayaksuraj/docker-pipe:1.0.0
      variables:
        DOCKER_REGISTRY: $DOCKER_REGISTRY
        DOCKER_REPOSITORY: $DOCKER_REPOSITORY
        DOCKER_USERNAME: $DOCKER_USERNAME
        DOCKER_PASSWORD: $DOCKER_PASSWORD
        IMAGE_TAG: "${IMAGE_TAG:-${BITBUCKET_COMMIT:0:7}}"
        DOCKERFILE_PATH: "./Dockerfile"
        BUILD_ARGS: "VERSION=${IMAGE_TAG:-${BITBUCKET_COMMIT:0:7}},BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ'),VCS_REF=${BITBUCKET_COMMIT}"
        SCAN_IMAGE: "true"
        TRIVY_SEVERITY: "${TRIVY_SEVERITY:-CRITICAL,HIGH}"
        TRIVY_EXIT_CODE: "${TRIVY_EXIT_CODE:-0}"
        PUSH_IMAGE: "true"
        DEBUG: "false"

    # ==========================================================================
    # Image Signing & SBOM Attachment (Cosign - not yet in docker-pipe)
    # ==========================================================================
    cosign-sign-sbom: &cosign-sign-sbom
      step:
        name: 🔐 Sign Image & Attach SBOM
        script:
          - export IMAGE_TAG="${IMAGE_TAG:-${BITBUCKET_COMMIT:0:7}}"
          - export IMAGE_FULL="$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"

          # Install Cosign and Syft (only tools not in docker-pipe)
          - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.2/cosign-linux-amd64
          - chmod +x cosign-linux-amd64 && mv cosign-linux-amd64 /usr/local/bin/cosign
          - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

          # Generate SBOM
          - echo "📦 Generating SBOM..."
          - syft $IMAGE_FULL -o cyclonedx-json > sbom-${IMAGE_TAG}.json

          # Sign image with Cosign (keyless)
          - echo "✍️ Signing image with Cosign..."
          - cosign sign --yes $IMAGE_FULL

          # Attach SBOM to image
          - echo "📎 Attaching SBOM to image..."
          - cosign attach sbom --sbom sbom-${IMAGE_TAG}.json $IMAGE_FULL
        artifacts:
          - sbom-*.json

    helm-package: &helm-package
      pipe: docker://nayaksuraj/helm-pipe:1.0.0
      variables:
        HELM_CHART_PATH: "${HELM_CHART_PATH:-../../helm-chart}"
        CHART_VERSION: "${CHART_VERSION:-1.0.${BITBUCKET_BUILD_NUMBER}}"
        HELM_REGISTRY: $HELM_REGISTRY
        HELM_REGISTRY_USERNAME: $HELM_REGISTRY_USERNAME
        HELM_REGISTRY_PASSWORD: $HELM_REGISTRY_PASSWORD
        LINT_CHART: "true"
        PACKAGE_CHART: "true"
        PUSH_CHART: "${HELM_PUSH:-true}"

    deploy: &deploy
      pipe: docker://nayaksuraj/deploy-pipe:1.0.0
      variables:
        ENVIRONMENT: "${DEPLOY_ENV}"
        NAMESPACE: "${DEPLOY_NAMESPACE}"
        KUBECONFIG: "${DEPLOY_KUBECONFIG}"
        IMAGE_TAG: "${IMAGE_TAG:-${BITBUCKET_COMMIT:0:7}}"
        WAIT_FOR_ROLLOUT: "true"
        HELM_CHART_PATH: "${HELM_CHART_PATH:-../../helm-chart}"
        HELM_VALUES_FILE: "${HELM_VALUES_FILE}"

    # ==========================================================================
    # Slack Notification (Uses slack-pipe - eliminates manual curl/formatting)
    # ==========================================================================
    notify: &notify
      pipe: docker://nayaksuraj/slack-pipe:1.0.0
      variables:
        SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
        MESSAGE: "${MESSAGE:-✅ Deployment completed successfully}"
        TITLE: "${TITLE:-Bitbucket Pipeline}"
        STATUS: "${STATUS:-success}"
        ENVIRONMENT: "${DEPLOY_ENV}"
        INCLUDE_COMMIT_INFO: "true"
        INCLUDE_BUILD_INFO: "true"
        DEBUG: "false"

pipelines:
  # ==============================================================================
  # Pull Request Pipeline
  # ==============================================================================
  pull-requests:
    '**':
      - step: *pre-checks

      # Matrix tests for configured Python versions
      - parallel:
          - step:
              <<: *unit-test
              name: 🧪 Tests (Py 3.9)
              image: python:3.9-slim
          - step:
              <<: *unit-test
              name: 🧪 Tests (Py 3.10)
              image: python:3.10-slim
          - step:
              <<: *unit-test
              name: 🧪 Tests (Py 3.11)
              image: python:3.11-slim
          - step:
              <<: *unit-test
              name: 🧪 Tests (Py 3.12)
              image: python:3.12-slim

      - parallel:
          - step: *type-check
          - step:
              <<: *security-scan
              variables:
                FAIL_ON_HIGH: "false"  # Warning only for PRs

  # ==============================================================================
  # Develop Branch Pipeline
  # ==============================================================================
  branches:
    develop:
      - step: *pre-checks

      - parallel:
          fail-fast: true
          steps:
            - step: {<<: *unit-test, name: "Tests 3.9", image: python:3.9-slim}
            - step: {<<: *unit-test, name: "Tests 3.10", image: python:3.10-slim}
            - step: {<<: *unit-test, name: "Tests 3.11", image: python:3.11-slim}
            - step: {<<: *unit-test, name: "Tests 3.12", image: python:3.12-slim}

      - parallel:
          - step: *type-check
          - step: *quality-scan
          - step:
              <<: *security-scan
              variables:
                FAIL_ON_HIGH: "false"

      # Docker build, scan, and push using docker-pipe
      - step: *docker-build

      # Sign image and attach SBOM
      - step: *cosign-sign-sbom

      - step:
          <<: *deploy
          variables:
            DEPLOY_ENV: "dev"
            DEPLOY_NAMESPACE: "development"
            DEPLOY_KUBECONFIG: $KUBECONFIG_DEV
            HELM_VALUES_FILE: "helm-values-dev.yaml"

      - step:
          <<: *notify
          variables:
            MESSAGE: "✅ Deployed to DEV"
            DEPLOY_ENV: "dev"
            STATUS: "success"

    # ==============================================================================
    # Main Branch Pipeline
    # ==============================================================================
    main:
      - step: *pre-checks

      - parallel:
          fail-fast: true
          steps:
            - step: {<<: *unit-test, name: "Tests 3.9", image: python:3.9-slim}
            - step: {<<: *unit-test, name: "Tests 3.10", image: python:3.10-slim}
            - step: {<<: *unit-test, name: "Tests 3.11", image: python:3.11-slim}
            - step: {<<: *unit-test, name: "Tests 3.12", image: python:3.12-slim}

      - parallel:
          - step:
              <<: *type-check
              variables:
                MYPY_FLAGS: "--strict --disallow-untyped-calls"
          - step:
              <<: *quality-scan
              variables:
                SONAR_QUALITY_GATE: "true"
          - step:
              <<: *security-scan
              variables:
                FAIL_ON_HIGH: "true"
                SAST_SCAN: "true"
                IAC_SCAN: "true"

      # Docker build, scan, and push (fail on vulnerabilities in main branch)
      - step:
          <<: *docker-build
          variables:
            TRIVY_EXIT_CODE: "1"

      # Sign image and attach SBOM
      - step: *cosign-sign-sbom

      - step: *helm-package

      - step:
          <<: *deploy
          variables:
            DEPLOY_ENV: "staging"
            DEPLOY_NAMESPACE: "staging"
            DEPLOY_KUBECONFIG: $KUBECONFIG_STAGING
            HELM_VALUES_FILE: "helm-values-staging.yaml"
          trigger: manual

      - step:
          name: 🏥 Health Check
          script:
            - sleep 30
            - curl -f ${STAGING_URL:-https://staging.example.com}/health || exit 1

      - step:
          <<: *notify
          variables:
            MESSAGE: "✅ Deployed to STAGING"
            DEPLOY_ENV: "staging"
            STATUS: "success"
            TITLE: "Staging Deployment"

  # ==============================================================================
  # Tagged Release Pipeline
  # ==============================================================================
  tags:
    'v*':
      - step: *pre-checks

      - parallel:
          fail-fast: true
          steps:
            - step: {<<: *unit-test, name: "Tests 3.9", image: python:3.9-slim}
            - step: {<<: *unit-test, name: "Tests 3.10", image: python:3.10-slim}
            - step: {<<: *unit-test, name: "Tests 3.11", image: python:3.11-slim}
            - step: {<<: *unit-test, name: "Tests 3.12", image: python:3.12-slim}

      - parallel:
          - step:
              <<: *type-check
              variables:
                MYPY_FLAGS: "--strict --disallow-untyped-calls --disallow-untyped-defs"
          - step:
              <<: *security-scan
              variables:
                FAIL_ON_HIGH: "true"

      # Docker build, scan, and push with version tag
      - step:
          <<: *docker-build
          variables:
            IMAGE_TAG: "${BITBUCKET_TAG#v}"
            TRIVY_EXIT_CODE: "1"

      # Sign image and attach SBOM
      - step:
          <<: *cosign-sign-sbom
          variables:
            IMAGE_TAG: "${BITBUCKET_TAG#v}"

      # Also tag as latest
      - step:
          name: 🏷️ Tag as Latest
          services: [docker]
          script:
            - export VERSION="${BITBUCKET_TAG#v}"
            - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$VERSION
            - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$VERSION $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
            - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            - cosign sign --yes $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest

      - step:
          <<: *helm-package
          variables:
            CHART_VERSION: "${BITBUCKET_TAG#v}"

      # Canary deployment
      - step:
          name: 🚀 Canary (10%)
          script:
            - export VERSION="${BITBUCKET_TAG#v}"
            - helm upgrade --install myapp ${HELM_CHART_PATH:-../../helm-chart}
                --namespace production
                --set image.tag=$VERSION
                --set canary.enabled=true
                --set canary.weight=10
                --wait --timeout=5m
          trigger: manual

      - step:
          name: 📊 Monitor Canary
          script:
            - sleep 300
            - echo "✅ Canary metrics OK"

      - step:
          name: 🚀 Production (100%)
          script:
            - export VERSION="${BITBUCKET_TAG#v}"
            - helm upgrade --install myapp ${HELM_CHART_PATH:-../../helm-chart}
                --namespace production
                --set image.tag=$VERSION
                --set canary.enabled=false
                --wait --timeout=10m
                --atomic
          trigger: manual

      - step:
          name: 🏥 Production Health
          script:
            - for i in {1..5}; do curl -f ${PROD_URL:-https://api.example.com}/health && break || sleep 10; done

      - step:
          <<: *notify
          variables:
            MESSAGE: "🎉 v${BITBUCKET_TAG#v} deployed to PRODUCTION"
            DEPLOY_ENV: "production"
            STATUS: "success"
            TITLE: "Production Release"
            MENTION_CHANNEL: "channel"
            CUSTOM_FIELDS: '{"Version":"${BITBUCKET_TAG#v}","Deployment":"Canary → Full Rollout"}'

  # ==============================================================================
  # Custom Pipelines
  # ==============================================================================
  custom:
    auto-fix:
      - step:
          name: 🔧 Auto-fix
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry
            - poetry install --no-interaction
            - poetry run black .
            - poetry run ruff check . --fix
            - poetry run isort .
            - |
              if ! git diff --quiet; then
                git config user.name "Bitbucket Pipeline"
                git config user.email "pipeline@bitbucket.com"
                git add .
                git commit -m "style: auto-fix formatting [skip ci]"
                git push origin HEAD:${BITBUCKET_BRANCH}
              fi

    security-audit:
      - step:
          <<: *security-scan
          variables:
            FAIL_ON_HIGH: "false"
            REPORT_FORMAT: "json,html"
