# ==============================================================================
# Customized Python Pipeline - Override Template Defaults
# ==============================================================================
# This example shows how to customize the reusable template
# ==============================================================================

image: python:3.12-slim

options:
  max-time: 60

definitions:
  caches:
    poetry: ~/.cache/pypoetry
    pip: ~/.cache/pip
    pre-commit: ~/.cache/pre-commit

  services:
    docker:
      memory: 3072

  # Import all reusable steps from template
  # (In a real scenario, you'd include the template file)
  steps:
    # ... all steps from python-reusable-template.yml ...
    # For this example, we'll define simplified versions

    pre-checks: &pre-checks
      step:
        name: 🔍 Pre-checks
        caches: [poetry, pip]
        script:
          - pip install --upgrade pip poetry
          - poetry check && poetry lock --check
          - poetry install --no-interaction
          - poetry run ruff check .

    unit-test: &unit-test
      step:
        name: 🧪 Tests
        caches: [poetry]
        script:
          - pip install --upgrade pip poetry
          - poetry install --no-interaction
          - poetry run pytest --cov=src --junitxml=test-results.xml
        artifacts:
          - test-results.xml
          - coverage.xml

pipelines:
  # ==============================================================================
  # CUSTOMIZATION EXAMPLE 1: Test Only Specific Python Versions
  # ==============================================================================
  pull-requests:
    '**':
      - step: *pre-checks

      # Override: Only test Python 3.11 and 3.12 (not 3.9, 3.10)
      - parallel:
          - step:
              <<: *unit-test
              name: 🧪 Tests (Python 3.11)
              image: python:3.11-slim
          - step:
              <<: *unit-test
              name: 🧪 Tests (Python 3.12)
              image: python:3.12-slim

  # ==============================================================================
  # CUSTOMIZATION EXAMPLE 2: Add Custom Steps
  # ==============================================================================
  branches:
    develop:
      - step: *pre-checks
      - step: *unit-test

      # Custom: Add integration tests
      - step:
          name: 🔗 Integration Tests
          services:
            - postgres
            - redis
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry
            - poetry install --no-interaction
            - poetry run pytest tests/integration/ --junitxml=integration-results.xml
          artifacts:
            - integration-results.xml

      # Custom: Performance benchmarks
      - step:
          name: 📊 Performance Benchmarks
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry
            - poetry install --no-interaction
            - poetry run pytest tests/benchmarks/ --benchmark-only

      # Continue with standard docker build, etc.

  # ==============================================================================
  # CUSTOMIZATION EXAMPLE 3: Override Deployment Strategy
  # ==============================================================================
  tags:
    'v*':
      - step: *pre-checks
      - step: *unit-test

      # Custom: Blue-Green deployment instead of canary
      - step:
          name: 🔵 Deploy Blue (Staging)
          script:
            - export VERSION="${BITBUCKET_TAG#v}"
            - helm upgrade --install myapp-blue ../../helm-chart
                --namespace production
                --set image.tag=$VERSION
                --set service.name=myapp-blue
                --wait
          trigger: manual

      - step:
          name: 🧪 Smoke Tests on Blue
          script:
            - curl -f https://myapp-blue.example.com/health
            - ./scripts/smoke-tests.sh https://myapp-blue.example.com

      - step:
          name: 🔄 Switch Traffic to Blue
          script:
            - kubectl patch service myapp -p '{"spec":{"selector":{"version":"blue"}}}'
          trigger: manual

      - step:
          name: 🟢 Remove Green
          script:
            - helm uninstall myapp-green --namespace production || true

  # ==============================================================================
  # CUSTOMIZATION EXAMPLE 4: Organization-Specific Custom Pipelines
  # ==============================================================================
  custom:
    # Custom: Publish to internal PyPI
    publish-internal:
      - step:
          name: 📦 Publish to Internal PyPI
          caches: [poetry]
          script:
            - poetry config repositories.internal $INTERNAL_PYPI_URL
            - poetry build
            - poetry publish -r internal -u $PYPI_USER -p $PYPI_PASSWORD

    # Custom: Performance profiling
    profile:
      - step:
          name: 🔍 Performance Profiling
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry
            - poetry install --no-interaction
            - poetry run py-spy record -o profile.svg -- python -m pytest tests/
          artifacts:
            - profile.svg

    # Custom: Dependency update check
    dependency-update:
      - step:
          name: 📦 Check Dependency Updates
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry
            - poetry show --outdated
            - poetry update --dry-run

    # Custom: License compliance check
    license-check:
      - step:
          name: ⚖️ License Compliance
          caches: [poetry]
          script:
            - pip install --upgrade pip poetry pip-licenses
            - poetry install --no-interaction
            - pip-licenses --format=json > licenses.json
            - ./scripts/check-license-compliance.sh licenses.json
          artifacts:
            - licenses.json

# ==============================================================================
# CUSTOMIZATION TIPS
# ==============================================================================
# 1. Always start with the template, then customize
# 2. Use YAML anchors (&) and aliases (*) to reuse steps
# 3. Override only what you need to change
# 4. Keep customizations minimal for easier maintenance
# 5. Document why you're overriding (e.g., "Custom: Blue-Green deployment")
# 6. Test customizations in a feature branch first
# ==============================================================================

# ==============================================================================
# VARIABLES YOU CAN OVERRIDE
# ==============================================================================
# Set these in your pipeline steps or repository variables:
#
# COVERAGE_THRESHOLD=90  # Default: 85
# MYPY_FLAGS="--strict --disallow-any-unimported"
# TRIVY_SEVERITY="HIGH,CRITICAL,MEDIUM"
# SONAR_ENABLED="false"
# SECURITY_FAIL_ON_HIGH="true"
# HELM_CHART_PATH="./k8s/helm"
# SLACK_WEBHOOK_URL=...
# ==============================================================================
