{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName | default (printf "%s-tls" (include "app.fullname" .)) }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef }}
    kind: {{ .Values.certificate.issuerKind | default "ClusterIssuer" }}
    {{- if .Values.certificate.issuerGroup }}
    group: {{ .Values.certificate.issuerGroup }}
    {{- end }}
  {{- if .Values.certificate.commonName }}
  commonName: {{ .Values.certificate.commonName }}
  {{- end }}
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
  - {{ . }}
  {{- end }}
  {{- with .Values.certificate.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.certificate.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  {{- with .Values.certificate.usages }}
  usages:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
