{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  host: {{ include "app.fullname" . }}
  {{- if .Values.istio.trafficPolicy }}
  trafficPolicy:
    {{- toYaml .Values.istio.trafficPolicy | nindent 4 }}
  {{- end }}
  {{- if .Values.istio.subsets }}
  subsets:
  {{- toYaml .Values.istio.subsets | nindent 4 }}
  {{- end }}
{{- end }}
