{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  minReplicaCount: {{ .Values.keda.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.keda.maxReplicas | default 10 }}
  {{- if .Values.keda.fallback }}
  fallback:
    {{- toYaml .Values.keda.fallback | nindent 4 }}
  {{- end }}
  {{- if .Values.keda.advanced }}
  advanced:
    {{- toYaml .Values.keda.advanced | nindent 4 }}
  {{- end }}
  triggers:
  {{- toYaml .Values.keda.triggers | nindent 4 }}
{{- end }}
