{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
  - {{ . }}
  {{- end }}
  {{- if .Values.istio.gateways }}
  gateways:
  {{- range .Values.istio.gateways }}
  - {{ . }}
  {{- end }}
  {{- end }}
  http:
  {{- if .Values.istio.http }}
  {{- toYaml .Values.istio.http | nindent 4 }}
  {{- else }}
  - route:
    - destination:
        host: {{ include "app.fullname" . }}
        port:
          number: {{ .Values.service.port }}
  {{- end }}
{{- end }}
